# fly.toml app configuration file generated for melt on 2023-07-31T21:44:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "melt"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
[processes]
  app = "npm run start"
  server = "node server.js"

[env]
  FIRST_APP_PORT = "3000"
  SECOND_APP_PORT = "3001"

#[[services]]
#  internal_port = 3001
#  protocol = "tcp"
#  [[services.ports]]
#    port = 3001
#  [services.concurrency]
#    type = "connections"
#    hard_limit = 1000
#
#[[services]]
#  internal_port = 3001
#  protocol = "tcp"
#  [[services.ports]]
#    port = 3001
#  [services.concurrency]
#    type = "connections"
#    hard_limit = 1000
#
#[[services]]
#  http_checks = []
#  internal_port = 8080
#  protocol = "tcp"
#  script_checks = []
#  [[services.ports]]
#    force_https = true
#    handlers = ["http"]
#    port = 80
#  [[services.ports]]
#    handlers = ["http", "tls"]
#    port = 443
#  [[services.tcp_checks]]
#    grace_period = "1s"
#    interval = "15s"
#    restart_limit = 0
#    timeout = "2s"